image: maven:4.0.0-openjdk-17

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

stages:
  - production

production:
#  type: deploy
  stage: production
#  image: maven:4.0.0-jdk17-alpine
  script:
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - master